use python 2.7 for pep8 venv
This seems required to avoid issues such as the following
which started to popup when py3 became the default:

  File "/home/zuul/src/opendev.org/openstack/networking-bagpipe/.tox/pep8/lib/python3.6/site-packages/astroid/builder.py", line 134, in file_build
    module = self._data_build(data, modname, path)
  File "/home/zuul/src/opendev.org/openstack/networking-bagpipe/.tox/pep8/lib/python3.6/site-packages/astroid/builder.py", line 177, in _data_build
    module = rebuilder.visit_module(node, modname, node_file, package)
  File "/home/zuul/src/opendev.org/openstack/networking-bagpipe/.tox/pep8/lib/python3.6/site-packages/astroid/rebuilder.py", line 148, in visit_module
    newnode.body = [self.visit(child, newnode) for child in node.body]
  File "/home/zuul/src/opendev.org/openstack/networking-bagpipe/.tox/pep8/lib/python3.6/site-packages/astroid/rebuilder.py", line 148, in <listcomp>
    newnode.body = [self.visit(child, newnode) for child in node.body]
  File "/home/zuul/src/opendev.org/openstack/networking-bagpipe/.tox/pep8/lib/python3.6/site-packages/astroid/rebuilder.py", line 161, in visit
    return self._transform(visit_method(node, parent))
  File "/home/zuul/src/opendev.org/openstack/networking-bagpipe/.tox/pep8/lib/python3.6/site-packages/astroid/rebuilder.py", line 238, in visit_assign
    newnode.value = self.visit(node.value, newnode)
  File "/home/zuul/src/opendev.org/openstack/networking-bagpipe/.tox/pep8/lib/python3.6/site-packages/astroid/rebuilder.py", line 161, in visit
    return self._transform(visit_method(node, parent))
  File "/home/zuul/src/opendev.org/openstack/networking-bagpipe/.tox/pep8/lib/python3.6/site-packages/astroid/rebuilder.py", line 329, in visit_callfunc
    newnode.func = self.visit(node.func, newnode)
  File "/home/zuul/src/opendev.org/openstack/networking-bagpipe/.tox/pep8/lib/python3.6/site-packages/astroid/rebuilder.py", line 161, in visit
    return self._transform(visit_method(node, parent))
  File "/home/zuul/src/opendev.org/openstack/networking-bagpipe/.tox/pep8/lib/python3.6/site-packages/astroid/rebuilder.py", line 551, in visit_getattr
    newnode.expr = self.visit(node.value, newnode)
  File "/home/zuul/src/opendev.org/openstack/networking-bagpipe/.tox/pep8/lib/python3.6/site-packages/astroid/rebuilder.py", line 161, in visit
    return self._transform(visit_method(node, parent))
  File "/home/zuul/src/opendev.org/openstack/networking-bagpipe/.tox/pep8/lib/python3.6/site-packages/astroid/rebuilder.py", line 331, in visit_callfunc
    if node.starargs is not None:
AttributeError: 'Call' object has no attribute 'starargs'

It seems reasonable to use python2.7 for such a job
of a stable branch.

Change-Id: Ifc1f2d4d6d622efe851c77bf0c4bddc34926c504